# Copyright (C) 2024 Project-ACT
# 
# This file is part of ov-tessellation.
# 
# ov-tessellation is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ov-tessellation is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ov-tessellation.  If not, see <https://www.gnu.org/licenses/>.

name: Feature
description: Agile Feature for project design and planning, a top-level grouping of User Stories
title: "[Feature]: "
labels: ["feature", "triage"]
projects: ["project-act/2"]
assignees:
  - DanHugoDanHugo
body:
  - type: markdown
    attributes:
      value: |
        # Agile Feature
        
        A Feature is a general, yet focused description of some aspect of a project to implemented
        during an Epic, detailed at a more granular level as a collection of one or more related User Stories.

        A Feature may also indicate an implementation requirement that can be further detailed with User Stories, 
        for example an OpenAPI implementation, 

  - type: markdown
    attributes:
      value: |
        # Description
        
  - type: textarea
    id: description
    attributes:
      label: A general description of some behavior, interface, experience, etc.
      description: To be described further with one or more User Stories…
      placeholder: A Feature might be an adjustable perpetual calendar, grouping User Stories about month and year flipping, etc.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # References
        
  - type: textarea
    id: references
    attributes:
      label: External specs documentation, RFCs, accepted standards, examples, etc
      description: To be described further with one or more User Stories…
      placeholder: |
        - Links to resources to aid in implementation of User Stories attached to this Feature
        - to External API Specifications, Accessibility Standards
        - to Verification/Certification tools
        - to Similar features in other projects/platforms

    validations:
      required: true
