name: User Story
description: Agile User story.
title: "[User Story]: "
labels: ["story"]
assignees:
  - DanHugoDanHugo
body:
  - type: markdown
    attributes:
      value: |
        # The 3 C´s of Agile User Stories
        
        Select a user and describe what they would like to accomplish with context,
        addressing questions such as What and Why. Then describe in list form how we know we met those expectations.

        A user story is a description of what to do, a task in a related repository will describe implementation of
        a particular user story. Multiple tasks in multiple repositories may implement a user story or stories.
        
  - type: markdown
    attributes:
      value: |
        User types for this project
        - **Project Manager** responsible for multiple repositories
        - **Repository Manager** responsible for one or few repositories
        - **Project Contributor** part of the organization
        - **External Contributor** not a part of the organization, discovering projects

  - type: markdown
    attributes:
      value: |
        Please compose Conversation and Confirmation elements in the first person, as though you are the User.
      
  - type: markdown
    attributes:
      value: "# Card"
  - type: dropdown
    id: card
    attributes:
      label: As a …
      description: Who are we listening to?
      options:
        - Project Manager
        - Repository Manager
        - Project Contributor
        - External Contributor
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# Conversation"
  - type: textarea
    id: conversation
    attributes:
      label: … I want to …
      description: What does the user want to accomplish?
      placeholder: Background, Context, and Detail
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# Confirmation"
  - type: textarea
    id: confirmation
    attributes:
      label: "… so that …"
      placeholder: |
        - A list
        - of confirmable
        - items
      description: How do we determine we met expectations?
    validations:
      required: true

