name: User Story
description: Agile User story.
title: "[User Story]: "
labels: ["story"]
assignees:
  - DanHugoDanHugo
body:
  - type: markdown
    attributes:
      value: "# Card"
  - type: dropdown
    id: card
    attributes:
      label: As a …
      description: Who are we listening to?
      options:
        - Project Manager
        - Repository Manager
        - Project Contributor
        - External Contributor
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# Conversation"
  - type: textarea
    id: conversation
    attributes:
      label: … I want to …
      description: What does the user want to accomplish?
      placeholder: Background, Context, and Detail
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# Confirmation"
  - type: textarea
    id: confirmation
    attributes:
      label: "… so that …"
      placeholder: |
        - A list
        - of confirmable
        - items
      description: How do we determine we met expectations?
    validations:
      required: true

