# Copyright (C) 2024 Project-ACT
# 
# This file is part of ov-tessellation.
# 
# ov-tessellation is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ov-tessellation is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ov-tessellation.  If not, see <https://www.gnu.org/licenses/>.

name: User Story
description: Agile User story for initiative design and planning
title: "[User Story]: Edit title after colon"
labels:
  - story
  - triage
projects:
  - Project-ACT/2
assignees:
  - DanHugoDanHugo
body:
  - type: markdown
    attributes:
      value: |
        # Agile User Story and the 3 Cs
        
        1. Select a User Card (imagine index cards, one color per user type).
        2. Describe in Conversation what this User would like to accomplish, with context, addressing concerns such as What and Why.
        3. Describe in simple list form (not checkboxes) Confirmation that we met those expectations as Acceptance Criteria.

        A user story is a description of what to do in somewhat abstract form, a task (issue) in a *related repository* will describe
        implementation of a particular User Story including Confirmation checks, which are essentially concrete **Key Results**.
        
        Multiple tasks in multiple repositories may implement a User Story or Stories.

# This displayed list of User types should match the dropdown list below
# Edit to match Agile User types for this initiative 
  - type: markdown
    attributes:
      value: |
        User types *for this initiative*:
        - **Organization Maintainer** responsible for a cohort of one or more people
        - **Organization Member** is anyone considered to be a part of an organization
        - **Project Maintainer** responsible for managing project(s)
        - **Project Contributor** a person who is part of an organization contributing to project(s)
        - **External Contributor** a person discovering projects
        - **Casual User** a curious person checking stuff out
        - **Automated User** a spider or other bot or similar
        - **Catalog Maintainer** oversees the gathered data from remote orgs and projects
        - **Spider Maintainer** oversees operation of the automation of gathering data from orgs and projects
        - **Visualization Maintainer** integrates graph visualizations into other platform(s)
        - **Notification Maintainer** manages integration of notifications with messaging tools and channels
        - **Tessellation Contributor** works on Tessellation components in any capacity

  - type: markdown
    attributes:
      value: |
        **Please compose Conversation and Confirmation elements in the first person, as though you are the selected User.**
      
  - type: markdown
    attributes:
      value: "# Card"

  - type: dropdown
    id: card
    attributes:
      label: As a …
      description: Who are we listening to?
# Options in this dropdown list should match the display list of User types above
      options:
        - Organization Maintainer
        - Organization Member
        - Project Maintainer
        - Project Contributor
        - External Contributor
        - Casual User
        - Automated User
        - Catalog Maintainer
        - Spider Maintainer
        - Visualization Maintainer
        - Notification Maintainer
        - Tessellation Contributor
      default: 0
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        # Conversation

        Typically this is literally a conversation regarding what a particular User
        might want, need, or expect from a particular Feature, which this User Story
        is describing.

  - type: textarea
    id: conversation
    attributes:
      label: … I want/need to …
      description: What does the user hope to accomplish from their perspective?
      placeholder: Background, Context, and Detail, optionally in list form, the results of discussion and pondering…
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Confirmation

        When a Feature becomes available for a User, a particular User Type may determine that
        the implementation is sufficient, close, or maybe not. Here we spell out specifics that
        this User Type might have examine to make that determination.

  - type: textarea
    id: confirmation
    attributes:
      label: … so that …
      placeholder: |
        - A list
        - of confirmable items
        - describing Acceptance Criteria
        - for this story
      description: How do we determine whether we met User expectations?
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Linked Issues"

  - type: markdown
    attributes:
      value: |
        Intra-Overview and Implementation Project Repository Linked Issue(s)"

        Issues should be linked by url (see info for issue linking bottom of page) to indicate
        graph relationship between them, with tags in a task list indicating the link relationship.
        Identifying relationships between issues within the initiative hierarchy should
        be easier than without this information.

        Tags and Linked Issues
        - feature: --> the parent Feature in this Agile hierarchy for this User Story
        - task: --> Implementation Task located in a separate repository
        - merge-to: --> a User Story that is a merging of this and other User Stories
        - merge-from: <-- a User Story that was merged into this User Story
        - split-to: --> a User Story that is one of multiple User Stories derived from this User Story
        - split-from: <-- a User Story that was split into this and other User Stories
        - spike-to: --> a virtual User Story for planning and estimation of related User Stories
        - spike-from: <-- a real User Story connected to a virtual spike User Story

        Merge-to and Split-to User Story issue(s) should be **Closed as Not Planned** in favor of the
        consolidated or expanded User Story issue(s), as appropriate. Do not delete, mark as merge
        or split and **Closed as Not Planned**.

  - type: textarea
    id: linking
    attributes:
      label: Linked Issues
      description: "Tag entries with epic: , task: , story: , merge-to: , split-from: , etc"
      placeholder: |
        - [ ] epic: issue link within overview
        - [ ] merge-to: this issue merges into a new issue
        - [ ] split-from: this issue is one refactor from a parent Theme issue

    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # References

        Links to external specs, documents, RFCs, accepted standards, examples, etc
        
  - type: textarea
    id: references
    attributes:
      label: References
      description: Place useful information close for implementors to find…
      placeholder: |
        - Links to resources to aid in implementation of this User Story
        - to External API Specifications, Accessibility Standards
        - to Verification/Certification tools
        - to Similar features in other Component Projects/Platforms

    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Notes

        Non-story knowledge and insight

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Optional meta detail
      placeholder: Useful information for planning and implementation, etc.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Wrap-Up

        Post-Story comments, observations, notes.

  - type: textarea
    id: wrapup
    attributes:
      label: Wrap-Up
      description: To aid in iterative process improvement and learning
      placeholder: |
        Anything that may contribute to other User Stories and other Initiative effort.

    validations:
      required: false

  - type: markdown
    attributes: 
      value: |
        ## Helpful Issue-filing Links
        - [Linking to Issues and PRs across Repositories](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests)
